<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="1" failed="4" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-06-16T11:29:58 CEST" name="Default suite" finished-at="2021-06-16T11:30:57 CEST" duration-ms="59339">
    <groups>
    </groups>
    <test started-at="2021-06-16T11:29:58 CEST" name="Default test" finished-at="2021-06-16T11:30:57 CEST" duration-ms="59339">
      <class name="projectTests.ProjectSignInTests">
        <test-method is-config="true" signature="preSihTestova()[pri:0, instance:projectTests.ProjectSignInTests@193f604a]" started-at="2021-06-16T11:29:58 CEST" name="preSihTestova" finished-at="2021-06-16T11:30:08 CEST" duration-ms="9893" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preSihTestova -->
        <test-method is-config="true" signature="startTest()[pri:0, instance:projectTests.ProjectSignInTests@193f604a]" started-at="2021-06-16T11:30:08 CEST" name="startTest" finished-at="2021-06-16T11:30:09 CEST" duration-ms="1858" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method signature="signinWithValidCredentials()[pri:0, instance:projectTests.ProjectSignInTests@193f604a]" started-at="2021-06-16T11:30:09 CEST" name="signinWithValidCredentials" finished-at="2021-06-16T11:30:12 CEST" duration-ms="2355" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signinWithValidCredentials -->
        <test-method is-config="true" signature="theEndTest()[pri:0, instance:projectTests.ProjectSignInTests@193f604a]" started-at="2021-06-16T11:30:12 CEST" name="theEndTest" finished-at="2021-06-16T11:30:14 CEST" duration-ms="2632" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- theEndTest -->
        <test-method is-config="true" signature="startTest()[pri:0, instance:projectTests.ProjectSignInTests@193f604a]" started-at="2021-06-16T11:30:14 CEST" name="startTest" finished-at="2021-06-16T11:30:17 CEST" duration-ms="2272" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method signature="signInWithInvalidEmail()[pri:5, instance:projectTests.ProjectSignInTests@193f604a]" started-at="2021-06-16T11:30:17 CEST" name="signInWithInvalidEmail" finished-at="2021-06-16T11:30:19 CEST" duration-ms="2747" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at projectPages.ProjectSignInPage.invalidEmailText(ProjectSignInPage.java:95)
at projectTests.ProjectSignInTests.signInWithInvalidEmail(ProjectSignInTests.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signInWithInvalidEmail -->
        <test-method is-config="true" signature="theEndTest()[pri:0, instance:projectTests.ProjectSignInTests@193f604a]" started-at="2021-06-16T11:30:19 CEST" name="theEndTest" finished-at="2021-06-16T11:30:24 CEST" duration-ms="4357" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- theEndTest -->
        <test-method is-config="true" signature="startTest()[pri:0, instance:projectTests.ProjectSignInTests@193f604a]" started-at="2021-06-16T11:30:24 CEST" name="startTest" finished-at="2021-06-16T11:30:26 CEST" duration-ms="2070" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method signature="signInWithInvalidPassword()[pri:10, instance:projectTests.ProjectSignInTests@193f604a]" started-at="2021-06-16T11:30:26 CEST" name="signInWithInvalidPassword" finished-at="2021-06-16T11:30:28 CEST" duration-ms="2513" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at projectPages.ProjectSignInPage.invalidPasswordText(ProjectSignInPage.java:99)
at projectTests.ProjectSignInTests.signInWithInvalidPassword(ProjectSignInTests.java:42)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signInWithInvalidPassword -->
        <test-method is-config="true" signature="theEndTest()[pri:0, instance:projectTests.ProjectSignInTests@193f604a]" started-at="2021-06-16T11:30:28 CEST" name="theEndTest" finished-at="2021-06-16T11:30:31 CEST" duration-ms="3029" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- theEndTest -->
        <test-method is-config="true" signature="startTest()[pri:0, instance:projectTests.ProjectSignInTests@193f604a]" started-at="2021-06-16T11:30:31 CEST" name="startTest" finished-at="2021-06-16T11:30:35 CEST" duration-ms="3145" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method signature="signInWithEmptyCredentials()[pri:15, instance:projectTests.ProjectSignInTests@193f604a]" started-at="2021-06-16T11:30:35 CEST" name="signInWithEmptyCredentials" finished-at="2021-06-16T11:30:39 CEST" duration-ms="4323" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at projectPages.ProjectSignInPage.emptyCredentialsText(ProjectSignInPage.java:103)
at projectTests.ProjectSignInTests.signInWithEmptyCredentials(ProjectSignInTests.java:52)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signInWithEmptyCredentials -->
        <test-method is-config="true" signature="theEndTest()[pri:0, instance:projectTests.ProjectSignInTests@193f604a]" started-at="2021-06-16T11:30:39 CEST" name="theEndTest" finished-at="2021-06-16T11:30:40 CEST" duration-ms="1479" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- theEndTest -->
        <test-method is-config="true" signature="startTest()[pri:0, instance:projectTests.ProjectSignInTests@193f604a]" started-at="2021-06-16T11:30:40 CEST" name="startTest" finished-at="2021-06-16T11:30:44 CEST" duration-ms="3550" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method signature="signOut()[pri:20, instance:projectTests.ProjectSignInTests@193f604a]" started-at="2021-06-16T11:30:44 CEST" name="signOut" finished-at="2021-06-16T11:30:51 CEST" duration-ms="6566" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at projectPages.ProjectSignInPage.invalidEmailText(ProjectSignInPage.java:95)
at projectTests.ProjectSignInTests.signInWithInvalidEmail(ProjectSignInTests.java:32)
at projectTests.ProjectSignInTests.signOut(ProjectSignInTests.java:57)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signOut -->
        <test-method is-config="true" signature="theEndTest()[pri:0, instance:projectTests.ProjectSignInTests@193f604a]" started-at="2021-06-16T11:30:51 CEST" name="theEndTest" finished-at="2021-06-16T11:30:57 CEST" duration-ms="6286" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- theEndTest -->
        <test-method is-config="true" signature="posleSihTestova()[pri:0, instance:projectTests.ProjectSignInTests@193f604a]" started-at="2021-06-16T11:30:57 CEST" name="posleSihTestova" finished-at="2021-06-16T11:30:57 CEST" duration-ms="144" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- posleSihTestova -->
      </class> <!-- projectTests.ProjectSignInTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
